### ISSUE TITLE
CSS-Transition、Web Animationを豊富にする

### ISSUE THREAD

**Issue by shundroid** [comozilla/Parapara-Canvas-Editor#15]
アニメーションが使えそうな場所
- [ ] menu.toggleOpenMenuButton -> display をただnoneにするのでなく、フワーッとやりたい
- [ ] フレームのUI -> ここはだいぶ行ける。
  - [ ] フレームを追加する部分
  - [ ] currentFrame を選択した時、出るボタンをボヨヨーンとやりたい

など。↑に提案があれば[Wiki](https://github.com/comozilla/Parapara-Canvas-Editor/wiki/%2315-%E5%AE%8C%E4%BA%86%E3%81%BE%E3%81%A7%E3%81%AE%E6%B5%81%E3%82%8C)まで

**Comment by shundroid** [comment]
JSからCSS-Transitionをする方法を書いておきますー！

## 1. CSS側でtransitionを使う宣言とアニメーションする内容を書く

（例）

``` css
#animate1 {
  transition: transform 0.25s cubic-bezier(.18,.89,1,1.7) 0s;
}
/* アニメーションする内容 */
.play-animate1 {
  transform: scale(1.8);
}
```

この時、アニメーションする内容のセレクタはクラスで指定しておきます。
transition の第１引数はアニメーションするプロパティ。
第３引数は、Firefoxについているアニメーションツールが便利です。

## 2. アニメーションする

``` js
document.getElementById("xxx").addEventListener("click", function() {
  // 再生
  document.getElementById("animate1").classList.add("play-animate1");

  // 逆再生（？）
  document.getElementById("animate1").classList.remove("play-animate1");
});
```

JS 側で、クラスを追加するとできます。
classList プロパティを使うと、add や remove、toggle といった便利な関数が使えるので、
使ってください！
